### ISSUE TITLE
Determine license

### ISSUE THREAD

**Issue by atcupps** [atcupps/Jupiterp#16]
By default, Jupiterp is under an all-rights-reserved copyright license. I think we should determine a different license to use and create a license document so rights to use and modify Jupiterp source code are explicit and clear. Unfortunately, I don't know much about licenses. Browsing [choosealicense.com](https://choosealicense.com/), I feel like [GPL 3.0](https://choosealicense.com/licenses/gpl-3.0/) might make sense for this project. Also noted, PlanetTerp, which is similar in scope and function to this project, uses [GNU Affero GPL v3.0](https://github.com/planetterp/PlanetTerp/blob/master/LICENSE).

**Comment by atcupps** [comment]
@alanliu2009 thoughts? I think it makes sense to have some restrictions on redistributions of Jupiterp but I also don't want to be too restrictive.

**Comment by alanliu2009** [comment]
Yeah this looks good, unless we want a warranty, in which case [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) might be suitable.
