### ISSUE TITLE
Create error pages

### ISSUE THREAD

**Issue by atcupps** [atcupps/Jupiterp#192]
Errors like 404 errors can be handled in SvelteKit using a `+error.svelte` page; this should be implemented. Currently if you visit an unknown page it only displays the navbar at the top which might be confusing.

**Comment by varungole** [comment]
Hey, I came here from reddit. As this project is open source, do you think I could contribute to it?

**Comment by atcupps** [comment]
@varungole for sure. Of course you can work on whatever you want but if you want to ask questions or better communicate about specifics or what might be good to work on in the project, you can message me on Discord; my username is `beizi`. Or if you don't have discord you could email admin@jupiterp.com and we could figure out some other way to communicate.

**Comment by varungole** [comment]
Sure!
 a little busy right now, after the spring break, I will start contributing to this project! Cheers
