### ISSUE TITLE
Determine cause of error in home `+page.ts`

### ISSUE THREAD

**Issue by atcupps** [atcupps/Jupiterp#5]
When department and course data is loaded as `deptsAndCourses` in base `+page.ts`, an error shows up for the `departments` field of the `load` function return:

```Type '{}' is missing the following properties from type 'Department[]': length, pop, push, concat, and 35 more.ts(2740)```

I could not figure out why this is an error; the source of this error should be determined and fixed.

**Comment by alanliu2009** [comment]
I think the problem is that deptsAndCourses is a string, and isn't parsed into the array form that departments is looking for.

**Comment by atcupps** [comment]
Since the code seems to be running fine, the cause may be that VSCode cannot tokenize the JSON file

**Comment by atcupps** [comment]
I tested whether tokenizing is the problem by making `departments.json` smaller; this fixed the issue, so I think the problem is just that VSCode doesn't tokenize large files and thus TypeScript cannot determine the type of the `json` import.
