### ISSUE TITLE
Design front-end user interface

### ISSUE THREAD

**Issue by atcupps** [atcupps/Jupiterp#8]
Create the design for the Jupiterp user interface; designs ideas and feedback can be listed below

**Comment by atcupps** [comment]
Idea for small-version logo, can be used in favicon.
<img src="https://github.com/atcupps/Jupiterp/assets/91998663/b1cdf407-748c-4ac9-8509-8ed43b38e0f6" alt="small logo" width="200"/>

**Comment by atcupps** [comment]
Idea for full logo, can go in top-left?
<img src="https://github.com/atcupps/Jupiterp/assets/91998663/2152450b-9e65-47ef-8ba9-c9aafbd134de" alt="full logo" width="400px">

**Comment by atcupps** [comment]
Feedback pls @alanliu2009 @meilin2468

**Comment by meilin2468** [comment]
LGTM

**Comment by alanliu2009** [comment]
LGTM

**Comment by atcupps** [comment]
Possible layout design with both light and dark modes; @alanliu2009 @meilin2468 feedback?

<img src="https://github.com/atcupps/Jupiterp/assets/91998663/a6921c0e-6e1b-4f86-8773-9cf0e2a9b576" width="700px">

<img src="https://github.com/atcupps/Jupiterp/assets/91998663/160e4739-66dc-4608-8536-1670c0e71de9" width="700px">

**Comment by atcupps** [comment]
Alternate light mode version with black borders around the classtimes:

<img src="https://github.com/atcupps/Jupiterp/assets/91998663/21d5cf55-a9c4-4fea-b469-347807df85ca" width="700px">

**Comment by alanliu2009** [comment]
I think it looks cleaner without the black borders.
Also the dark mode could have a more gray background instead of just black.

**Comment by atcupps** [comment]
@alanliu2009 how about this?

<img src="https://github.com/atcupps/Jupiterp/assets/91998663/7e00d84b-4f9e-45d9-9cfc-c46fd2e2b597" width="700px">

**Comment by atcupps** [comment]
Also take a look at the darkened background on course names you suggested:

<img src="https://github.com/atcupps/Jupiterp/assets/91998663/97d818ad-1282-4525-8f26-f33983fb7542" width="700px">

<img src="https://github.com/atcupps/Jupiterp/assets/91998663/b49daef6-8ebb-490e-8a20-4bef30982207" width="700px">

**Comment by alanliu2009** [comment]
Yeah I like the darkened course names, LGTM.
